### ISSUE TITLE
Sorting in plugin doesn't match sorting in RSS feed

### ISSUE THREAD

**Issue by brqkke** [rhyswynne/ebay-feeds-for-wordpress#11]
I have created a rss feed on the eBay partner network.
As sort criterium I have picked: price: highest first.
When I use the ebay-for-wordpress plugin the sorting is ignored and the show up in a random order.

**Comment by brqkke** [comment]
example: http://rest.ebay.com/epn/v1/find/item.rss?keyword=watch&categoryId1=31387&sortOrder=PricePlusShippingHighest&programid=1&campaignid=5338093268&toolid=10039&maxPrice=1.0E7&minPrice=300000.0&listingType1=AuctionWithBIN&listingType2=FixedPrice&descriptionSearch=true&feedType=rss&lgeo=1

**Comment by rhyswynne** [comment]
Hi there,

The latest push - https://github.com/rhyswynne/ebay-feeds-for-wordpress/archive/master.zip - should have fixed this issue.

Please test and I'll close the issue.

**Comment by rhyswynne** [comment]
Closing the issue as confident version 2.2 fixes this.

**Comment by brqkke** [comment]
Correct.
After update the problem is solved.
THX
